### ISSUE TITLE
Error in PHP 8: Unparenthesized `a ? b : c ? d : e` is not supported

### ISSUE THREAD

**Issue by jlahijani** [adrianbj/PageProtector#6]
I have this module in a non-enabled/non-installed state on a site that I recently upgraded to PHP 8, and I got this error in PW's error log (the site 500's):

```
2021-01-01 22:45:07	guest	https://website.com/	Compile Error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` (line 389 of /var/www/website.com/public_html/site/assets/cache/FileCompiler/site/modules/PageProtector/PageProtector.module.php)
```

**Comment by adrianbj** [comment]
Hi @jlahijani - thanks for the report. I am running PHP 8 here as well and not seeing that error. The strange thing is that the ternary operator on that line is only a single `a ? b : c` - it's not nested so I am not sure why your system is throwing that error because it's only supposed to be for nested ternaries. 

Any chance you could investigate why this might be happening please? Maybe wrapping the entire ternary expression in parentheses will fix the error, but I don't think it should be happening in the first place.

Unrelated, but I did just discover some other PHP8 issues, so please update to the latest version.

**Comment by jlahijani** [comment]
I updated to the latest version and the issue went away.

Note: I'm not entirely sure why that error occurred in the first place.  I had 2 sites with on the same server with the exact same modules (both not installed).  One errored.  One didn't.  So who knows.

**Comment by adrianbj** [comment]
Yeah, it's confusing for sure - especially with it uninstalled. I almost feel like maybe the file compiler is responsible somehow, but who knows. Anyway, let me know if you see it again.
